# server configuration
server:
  port: 8443
  ssl:
    key-store: classpath:sssigned.jks
    key-password: sssigned123
    key-store-password: sssigned123

# datasource
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    url: jdbc:mysql://159.65.151.71:3306/springsecurity

  # JPA auto create
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect

# JWT configuration
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

# API path config
app:
  api:
    rest:
      root: /api/rest/v1
